//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techspire_LMS.Pages
{
    public partial class CourseDetails
    {
        protected global::System.Web.UI.WebControls.PlaceHolder phNotFound;
        protected global::System.Web.UI.WebControls.PlaceHolder phCourse;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Literal litCategory;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litMeta;
        protected global::System.Web.UI.WebControls.Repeater rptTags;
        protected global::System.Web.UI.WebControls.Literal litDescription;
        protected global::System.Web.UI.WebControls.PlaceHolder phRoadmap;
        protected global::System.Web.UI.WebControls.Literal litRoadmap;
        protected global::System.Web.UI.WebControls.PlaceHolder phProjects;
        protected global::System.Web.UI.WebControls.Literal litProjects;
        protected global::System.Web.UI.WebControls.PlaceHolder phGuestPrompt;
        protected global::System.Web.UI.WebControls.PlaceHolder phEnrolAction;
        protected global::System.Web.UI.WebControls.Button btnEnrol;
        protected global::System.Web.UI.WebControls.PlaceHolder phEnrolled;
        protected global::System.Web.UI.WebControls.Literal litProgress;
        protected global::System.Web.UI.WebControls.Repeater rptLessons;
        protected global::System.Web.UI.WebControls.Literal litNoLessons;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
        protected global::System.Web.UI.WebControls.Literal litNoQuizzes;
    }
}
